### PR TITLE
#42 Added Access domain and Project access classes.

### PR DESCRIPTION
**Pull request by gbalcewicz**
Just docs and tests missing, but you can start reviewing :)

### CODE REVIEW

**Comment by gbalcewicz** [comment]
@uc-group/bear-it ready for review

**Comment by mariuszniemiec** [comment]
Hi @gbalcewicz 
Other than my input from my last comment - I tried to test this branch locally.
Do I need to make any actions on DB/project build?
Straight branch switch caused me a fatal exception in login process. 

Zrzut ekranu z 2019-10-23 21-28-07

**Comment by gbalcewicz** [comment]
I disagree that tests should go separate. But I could add first the API and then refactor the current code base. Unfortunately I was building it while refactor and it wouldn't be much smaller. I will try better on PR next after the next one, because the next one will be big also :P.

**Comment by mariuszniemiec** [comment]
Well the bigger they are, the harder it is. Especialy in my case of not (yet) following project on daily basis.
Only missing (obcious) info for morons like me was to run `composer install` ;)
As always good work.

**Pull request merged**
